### ISSUE TITLE
Cannot tar Jxvf rostlab-data.txz

### ISSUE THREAD

**Issue by davidfstein** [Rostlab/predictprotein-docker#2]
downloaded via
```
wget -O rostlab-data.txz "http://www.rostlab.org/services/ppmi/download_file?format=gzip&file_to_download=db"
```

tar JXvf rostlab-data.txz
```
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

file rostlab-data.txz
```
rostlab-data.txz: data
```

I've tried unzipping first with xz -d rostlab-data.txz to no avail. Any advice?

**Comment by T1mK** [comment]
Thanks for contacting us, and apologies for the late answer - I just saw this issue. I checked the archive, and it is indeed corrupted. A new archive is being built now, but has not yet finished. As soon as it's finished, I'll update this issue. Thanks!

**Comment by T1mK** [comment]
Alright, it should be fixed now. There was a database error, which needed to be corrected. I was able to download and test the archive successfully from my end. Could you please give it a try?
