### ISSUE TITLE
individual function

### ISSUE THREAD

**Issue by Ma-hz** [Rostlab/predictprotein-docker#3]
Could PredictProtein be disassembled into a separate function? For example, I only want to predict the disulfide bond.

**Comment by T1mK** [comment]
Yes, for at least some of the individual methods. However, I've not tested this out myself, and am summarizing this after reading the documentation. Therefore, you'll probably have to play around with these options until you find what works for you.

If you run the docker image explicitly calling the `predictprotein` program command using arguments, you may input the method you want to individually run, along with that method's arguments using the `predictprotein` option `--method`.

From the `predictprotein` documentation:
```
       --method
           Describes method control parameters and requests methods to run when --target is not all. Format example:

            --method=norsp,win=50

           * begin with the method name, e.g. `norsp'

           * list method control parameters, e.g. win=50

           Not all methods support passing control parameters in this way due to their primitive command line interfaces.
```

For `disulfinder`, the `predictprotein` command would be something like this, using the relevant `disulfinder` options (in this example, I just used the `alternatives` option for `disulfinder`) that you require:

```
predictprotein --seqfile /usr/share/doc/predictprotein/examples/tquick.fasta --method=disulfinder,alternatives=3 --output-dir /tmp/pp
```

**Remember** - the paths you use as arguments are those that exist in the running docker container, not those on your docker host. Therefore, make sure your input and output directories are mapped to your docker host.

The options for the `disulfinder` method are as follows:
```
           OPTIONS
       -a, --alternatives=NUMBER
           alternative connectivity patterns (default=3)

       -o, --output=DIR
           output dir where predictions will be saved (default=$PWD)

       -p, --psi2=FILE|DIR
           input in psi2 format (PSI-BLAST Matrix in ASCII), either a single file or a directory(?). Generate this with "blastpgp -j <N> -Q FILE" where N
           >= 2.

       -r, --rootdir=DIR
           work directory (default=~/disulfinder)

       -k, --pkgdatadir=DIR
           package data directory containing Models (default=/usr/share/disulfinder)

       -F, --format={html|ascii}
           output format type (default=ascii)

       -d --blastdb=DIR
           blastpgp -d option (default=/data/sp+trembl)

       -c, --cleanpred
           cleanup intermediate prediction files (default=false)

       -P, --usepssm
           use pssm instead of counts for profiles (default=false)

       -C, --knownbondingstate
           assume bonding state is known (one file for each chain in directory <rootdir>/Predictions/Bondstate/Viterbi)     (default=false)

       -v, --version
           disulfinder version

       -?, --help
           help screen
```
