### ISSUE TITLE
Download Question

### ISSUE THREAD

**Issue by Ma-hz** [Rostlab/predictprotein-docker#4]
Hello，Could non-root users download and use this software.

**Comment by T1mK** [comment]
Anyone may download this software and use it, from our perspective. Regarding your compute environment, however, the answer depends on how your system is configured. A default docker installation will require the running user account to be in the group `docker`. This does, however, give the user account increased access, which many multi-user systems don't permit to general users. 

An alternative to the default Docker install, would be to [run the Docker daemon as a non-root user (Rootless mode) ](https://docs.docker.com/engine/security/rootless/)

Theoretically, if you're really looking to put in some effort, you could use a VM or other computer, install Debian Jessie on it, and then follow the Docker build recipe and included packages to get a functioning PredictProtein system running.
